--- 
- name: Install Apache.
  hosts: linhost
  gather_facts: no
  become: true 
  tasks:
     - name: Install Apache.
       yum:
         name:
           - httpd
           - httpd-devel
         state: present

     - name: Copy configuration files.
       copy:
         src: "{{ item.src }}"
         dst: "{{ item.dest }}"
         owner: root
         group: root
         mode: 0644
       with_items:
           - src: httpd.conf
             dest: /etc/httpd/conf/httpd.conf
           - src: httpd-vhosts.conf
             dest: /etc/httpd/conf/httpd-vhosts.conf

     - name: Start Apache
       service:
          name: httpd
          state: restarted
          enabled: true